import { BrandMark, MondayLogo } from "../shared.jsx";

export function Shell({ children }) { return <div className="flex min-h-[100dvh] justify-center bg-[#F5F0E6] text-[#072D1D] antialiased"><div className="min-h-[100dvh] w-full max-w-md">{children}</div></div>; }
export function PageFrame({ children }) { return <div className="flex h-[100svh] max-h-[100svh] flex-col overflow-hidden bg-[#F5F0E6] px-4 pb-0 pt-1.5">{children}</div>; }
export function Footer() { return <footer className="mt-auto h-[38px] shrink-0 bg-[#F5F0E6] pt-1 text-center"><div className="flex h-full items-start justify-center border-t border-[#0B5F35]/12 pt-1.5"><BrandMark /></div></footer>; }
export function GreenCard({ children }) { return <section className="rounded-[1.75rem] border border-white/10 bg-[#0B5F35] p-4 text-[#F5F0E6]">{children}</section>; }
export function Hero() { return <div className="flex h-[74px] shrink-0 flex-col items-center justify-center text-center"><div className="text-[9px] font-semibold uppercase tracking-[0.24em] text-[#0B5F35]/45">THE JOURNEY BEGINS</div><div className="mt-1.5 text-[32px] font-black uppercase leading-[0.9] tracking-[-0.015em] text-[#0B5F35]">CHOOSE A TEAM</div></div>; }
export function BottomTagline() { return <div className="flex min-h-[24px] shrink-0 items-center justify-center py-1 text-center"><p className="inline-block whitespace-nowrap text-[8px] font-bold uppercase tracking-[0.11em] text-[#072D1D]/45">PICK A TEAM · TAKE YOUR CHANCES · LIFT THE CUP</p></div>; }
export function SelectionLayout({ children }) { return <Shell><PageFrame><header className="shrink-0 text-center"><div className="flex h-[132px] items-center justify-center overflow-hidden"><MondayLogo /></div><Hero /></header><main className="flex min-h-0 flex-1 flex-col py-0"><div className="mt-1.5 shrink-0">{children}</div><BottomTagline /></main><Footer /></PageFrame></Shell>; }
export function DrawerShell({ children }) { return <div className="fixed inset-0 z-50 bg-[#F5F0E6]"><div className="mx-auto flex h-[100dvh] max-w-md flex-col px-5 pb-0 pt-3">{children}<Footer /></div></div>; }
